//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovaya.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(("Data Source=DESKTOP-8PI9E0E\\SQLEXPRESS01;Initial Catalog=kursovaya;Integrated Sec" +
            "urity=True;Connect Timeout=30;Encrypt=False;"))]
        public string bd_connect {
            get {
                return ((string)(this["bd_connect"]));
            }
            set {
                this["bd_connect"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute(("Data Source=DESKTOP-8PI9E0E\\SQLEXPRESS01;Initial Catalog=kursovaya;Integrated Sec" +
            "urity=True;Encrypt=False"))]
        public string kursovayaConnectionString {
            get {
                return ((string)(this["kursovayaConnectionString"]));
            }
        }
    }
}
